apiVersion: v1
kind: Service
metadata:
  name: svc-order-service
  labels:
    version: dev
    product: order-service
spec:
  selector:
    app: order-service
  type: ClusterIP
  ports:
    - port: 8880
      targetPort: 8880
      protocol: TCP
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-order-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: tmoechel/order-service:1.0
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8880
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          ports:
            - containerPort: 8880