apiVersion: v1
kind: Service
metadata:
  name: svc-delivery-service
  labels:
    version: dev
    product: delivery-service
spec:
  selector:
    app: delivery-service
  type: ClusterIP
  ports:
    - port: 8880
      targetPort: 8880
      protocol: TCP
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-delivery-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
        - name: delivery-service
          image: futuratechdemoacr.azurecr.io/delivery-service:1.2
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8880
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: MessageBroker__Broker__RabbitMq__Host
              value: rabbitmq-buyer
            - name: MessageBroker__Broker__RabbitMq__VirtualHost
              value: /
            - name: MessageBroker__Broker__RabbitMq__Username
              value: rabbitmq-user
            - name: MessageBroker__Broker__RabbitMq__Password
              value: rabbitmq-password
          ports:
            - containerPort: 8880
