using Shared;

namespace FS.TechDemo.BuyerBFF.GraphQL.Types.Order;


// OrderResponse is the GRPC autogenerated type
public class OrderType : ObjectType<OrderResponse>
{
    protected override void Configure(IObjectTypeDescriptor<OrderResponse> descriptor)
    {
        base.Configure(descriptor);
        descriptor.Field(context => context.Id).Description("Id of the Recipe");
        descriptor.Field(context => context.Name).Description("Name of the Recipe");
        descriptor.Field(context => context.Description).Description("Description of the Recipe");
    }
}