version: '3.4'

services:
    mysql:
        hostname: mysql
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: Admin@123+
        restart: unless-stopped
        ports:
            - 3306:3306
        volumes:
            - mysql-db:/var/lib/mysqlquartz
            
    rabbitmq:
        hostname: rabbitmq
        image: masstransit/rabbitmq:3
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=rabbitmq-user
            - RABBITMQ_DEFAULT_PASS=rabbitmq-password
            - RABBITMQ_DEFAULT_VHOST=/
        restart: unless-stopped
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
            - rabbitmq-log:/var/log/rabbitmq   
            
    quartz:
        hostname: quartz
        image: masstransit/quartz:latest
        ports:
            - 5002:80
        environment:
            - MT_Scheduler=quartz
            - MT_Quartz__ConnectionString=Server=tcp:mysql;Port=3306;Database=quartz;Uid=root;Pwd=Admin@123+
    
    seq:
        image: datalust/seq:latest
        container_name: 'seq'
        ports:
            - 5341:80
        environment:
            - ACCEPT_EULA=Y
        restart: unless-stopped
        
volumes:
    mysql-db: null
    rabbitmq-data: null
    rabbitmq-log: null
    