version: '3.4'

services:
    mysql:
        hostname: mysql
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: w4XmQMDbZmvBuvUg
        restart: unless-stopped
        ports:
            - 3306:3306
        volumes:
            - mysql-db:/var/lib/mysqlquartz
            
    rabbitmq:
        hostname: rabbitmq
        image: masstransit/rabbitmq
        container_name: 'rabbitmq'
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=rabbitmq-user
            - RABBITMQ_DEFAULT_PASS=rabbitmq-password
            - RABBITMQ_DEFAULT_VHOST=/
        restart: unless-stopped
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
            - rabbitmq-log:/var/log/rabbitmq         
    
    seq:
        image: datalust/seq:latest
        container_name: 'seq'
        ports:
            - 5341:80
        environment:
            - ACCEPT_EULA=Y
        restart: unless-stopped
        
volumes:
    mysql-db: null
    rabbitmq-data: null
    rabbitmq-log: null
    